"""Tests for detecting a generated layer produced by an older generator.

A wheel has no post-install hook, so `uv tool install` cannot run the
build itself. The generated modules also survive a reinstall, because
they are not part of the wheel. Without a stamp the tool would keep
running commands generated by whatever version happened to build them.
"""

from __future__ import annotations

import json

import pytest

from te_api import builder


@pytest.fixture
def layer(tmp_path, monkeypatch):
    """A generated layer in a temp dir, standing in for te_api/api_ro."""
    api_dir = tmp_path / "api_ro"
    api_dir.mkdir()
    monkeypatch.setattr(builder, "_api_dir", lambda read_only: api_dir)
    return api_dir


@pytest.fixture
def credentials(monkeypatch):
    """Configured OAuth2 credentials, so the build path is reachable."""
    from te_api.config import Config

    monkeypatch.setattr(Config, "CLIENT_ID", "id", raising=False)
    monkeypatch.setattr(Config, "CLIENT_SECRET", "secret", raising=False)


def _generated(api_dir):
    (api_dir / "registry.py").write_text("# generated\n")


# -- fingerprint --


def test_fingerprint_is_stable():
    assert builder.builder_fingerprint() == builder.builder_fingerprint()
    assert len(builder.builder_fingerprint()) == 16


# -- is_built / is_generated --


def test_nothing_generated(layer):
    assert builder.is_generated(True) is False
    assert builder.is_built(True) is False


def test_generated_by_this_builder_is_current(layer):
    _generated(layer)
    builder.write_build_stamp(layer)

    assert builder.is_generated(True) is True
    assert builder.is_built(True) is True


def test_generated_by_another_builder_is_stale(layer):
    """The upgrade case: files present, produced by a different version."""
    _generated(layer)
    (layer / builder.BUILD_STAMP_FILE).write_text(json.dumps({"builder": "0000old0000"}))

    assert builder.is_generated(True) is True
    assert builder.is_built(True) is False


def test_layer_without_a_stamp_is_stale(layer):
    """Anything generated before stamping existed must be rebuilt once."""
    _generated(layer)

    assert builder.is_built(True) is False


def test_corrupt_stamp_is_stale(layer):
    _generated(layer)
    (layer / builder.BUILD_STAMP_FILE).write_text("not json{")

    assert builder.is_built(True) is False


# -- ensure_api_built --


def test_current_layer_is_left_alone(layer, credentials, monkeypatch):
    _generated(layer)
    builder.write_build_stamp(layer)
    monkeypatch.setattr(
        builder, "download_spec", lambda _url: pytest.fail("should not download")
    )

    assert builder.ensure_api_built(True) is False


def test_stale_layer_is_rebuilt(layer, credentials, monkeypatch):
    _generated(layer)
    (layer / builder.BUILD_STAMP_FILE).write_text(json.dumps({"builder": "0000old0000"}))

    built = {}
    monkeypatch.setattr(builder, "download_spec", lambda _url: {"paths": {}})
    monkeypatch.setattr(
        builder,
        "generate_from_spec",
        lambda *a, **kw: built.setdefault("done", True),
    )

    assert builder.ensure_api_built(True) is True
    assert built == {"done": True}


def test_stale_layer_survives_missing_credentials(layer, monkeypatch, capsys):
    """An upgrade must not leave someone without a tool when offline."""
    from te_api.config import Config

    _generated(layer)
    (layer / builder.BUILD_STAMP_FILE).write_text(json.dumps({"builder": "0000old0000"}))
    monkeypatch.setattr(Config, "CLIENT_ID", "", raising=False)
    monkeypatch.setattr(Config, "CLIENT_SECRET", "", raising=False)

    assert builder.ensure_api_built(True) is False
    assert "could not regenerate" in capsys.readouterr().err


def test_stale_layer_survives_a_download_failure(layer, credentials, monkeypatch, capsys):
    _generated(layer)
    (layer / builder.BUILD_STAMP_FILE).write_text(json.dumps({"builder": "0000old0000"}))

    def _boom(_url):
        raise ConnectionError("no route to host")

    monkeypatch.setattr(builder, "download_spec", _boom)

    assert builder.ensure_api_built(True) is False
    err = capsys.readouterr().err
    assert "could not regenerate" in err
    assert "no route to host" in err


def test_missing_layer_without_credentials_exits(layer, monkeypatch):
    """With nothing generated there is no CLI to fall back to."""
    from te_api.config import Config

    monkeypatch.setattr(Config, "CLIENT_ID", "", raising=False)
    monkeypatch.setattr(Config, "CLIENT_SECRET", "", raising=False)

    with pytest.raises(SystemExit) as exc:
        builder.ensure_api_built(True)
    assert exc.value.code == 1


def test_missing_layer_propagates_a_download_failure(layer, credentials, monkeypatch):
    """Nothing to fall back to, so the error must not be swallowed."""

    def _boom(_url):
        raise ConnectionError("no route to host")

    monkeypatch.setattr(builder, "download_spec", _boom)

    with pytest.raises(ConnectionError):
        builder.ensure_api_built(True)


# -- the stamp is written by a real generation --

_MINIMAL_SPEC = {
    "paths": {
        "/v1/things/": {
            "get": {
                "operationId": "v1_things_list",
                "tags": ["things"],
                "summary": "List things",
                "parameters": [
                    {
                        "name": "filters",
                        "in": "query",
                        "required": True,
                        "schema": {"type": "string"},
                        "description": "Filters",
                    }
                ],
            }
        }
    }
}


def test_generate_from_spec_writes_the_stamp(tmp_path):
    out = tmp_path / "api"
    builder.generate_from_spec(_MINIMAL_SPEC, str(out), read_only=True, log=lambda _m: None)

    assert (out / "registry.py").exists()
    assert builder.read_build_stamp(out) == builder.builder_fingerprint()
    assert builder.is_built.__doc__  # sanity: the public API is the stamped one


def test_a_real_generation_is_recognised_as_current(tmp_path, monkeypatch):
    """End to end: generate, then have is_built agree it is up to date."""
    out = tmp_path / "api"
    builder.generate_from_spec(_MINIMAL_SPEC, str(out), read_only=True, log=lambda _m: None)
    monkeypatch.setattr(builder, "_api_dir", lambda read_only: out)

    assert builder.is_built(True) is True


def test_generated_command_offers_the_file_option(tmp_path):
    """The stamp exists to catch exactly this kind of drift."""
    out = tmp_path / "api"
    builder.generate_from_spec(_MINIMAL_SPEC, str(out), read_only=True, log=lambda _m: None)

    source = (out / "things.py").read_text()
    assert "@click.option('--file', 'param_file'" in source
    assert "load_param_file" in source


def test_empty_spec_generates_nothing(tmp_path):
    """Nothing to stamp, and is_built must not claim otherwise."""
    out = tmp_path / "api"
    builder.generate_from_spec({"paths": {}}, str(out), read_only=True, log=lambda _m: None)

    assert not (out / "registry.py").exists()
    assert builder.read_build_stamp(out) is None


def test_stamp_file_is_hidden_so_it_is_not_importable():
    """The stamp lives beside command modules; it must not look like one."""
    assert builder.BUILD_STAMP_FILE.startswith(".")
    assert not builder.BUILD_STAMP_FILE.endswith(".py")
